# Numpy Assignment:

# Questions 1:

Students are expected to make a notebook on the above function which must have a proper explanation
of the function,its syntax, its code, and its application(where do you think it will be useful. This application
part is optional; however, learners are advised to it to as much extent as possible .

# EigenValues and Eigenvectors of an array
 The function returns two values. First is Eigenvalus and second is eigenvectors
 
 Syntax:np.linalg.eig()
 

In [8]:
# Importing library
import numpy as np

n= np.array([[3,4],[5,6]])
print(n, "\n")
      
#finding eigenvalues and eigen vectors
x, y= np.linalg.eig(n)      
      
#printing eigen values
print("print the Eigen values of the given array: \n", x)

#printing eigen vectors
print("Print Eigen vectors of the given array:", y)
      

[[3 4]
 [5 6]] 

print the Eigen values of the given array: 
 [-0.21699057  9.21699057]
Print Eigen vectors of the given array: [[-0.77925158 -0.54107946]
 [ 0.62671124 -0.84097147]]


# digitize()
This function helps in getting the indices of the bin to which each value of the input array belongs and it returns an array containing the indices of the bin.

Syntax: np.digitize(Array,Bin,Right/left)

In [9]:
#import numpy
import numpy as np

a = np.array([1.5, 2.5, 5.6, 7.8,])
bins = np.array([1.0,1.4,2.4,4.5,8.7])

#using np.digitize()
x=np.digitize(a, bins)

print(x)

[2 3 4 4]


# repeat()

This is afunction used to repeat elements in an array

Syntax:np.repeat(a,repeats, axis)

In [10]:
import numpy as np
np.repeat(6,4)

array([6, 6, 6, 6])

In [11]:
b = np.array([[3,4], [7,8]])
np.repeat(b,5)

array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8])

# squeeze()
The squeeze()function is used to remove single-dimensional entries from the shape of an array

Syntax: np.squeeze(arr, axis=None)

In [12]:
import numpy as np
arr=np.array([[[3,4,5], [6,7,8]]])

print("Input array : ", arr)
print("Shape of input array :", arr.shape)

arr2 = np.squeeze(arr)

print("output  squeezed array :" , arr2)
print("Shape of output array : ", arr2.shape)

Input array :  [[[3 4 5]
  [6 7 8]]]
Shape of input array : (1, 2, 3)
output  squeezed array : [[3 4 5]
 [6 7 8]]
Shape of output array :  (2, 3)


# linspace()

It returns evenly spaced numbers over a specified interval.

Syntax: np.linspace(start,stop, num, endpoint, retstep)

In [13]:
import numpy as np 

# restep set to true
print("B\n", np.linspace(3.0, 4.0, num =6, retstep=True))

B
 (array([3. , 3.2, 3.4, 3.6, 3.8, 4. ]), 0.2)


# clip()
Its a function used to limit(clip) values in an array, where there is interval given and  some values are outside the values get clipped to the interval edge.

Syntax:np.clip(array, a_min,a_max)

In [14]:
import numpy as np
arry = [1,2,4,5,6,7,8,9]
print("Input array : ", arry)

arry1= np.clip(arry, a_min=2, a_max=5)
print("Output array :", arry1)

Input array :  [1, 2, 4, 5, 6, 7, 8, 9]
Output array : [2 2 4 5 5 5 5 5]




# extract()

Extract function returns the elements of an array that satisfy some condition.

Syntax: np.extract(condition,arr)

In [15]:
import numpy as np

a = np.array([ 2,3,4,5,6])
condition = (a<=6) & (a>2)

a2 = np.extract(condition,a)
print(a2)

[3 4 5 6]



# argpartition()

The function is used to cretaee an iderecre partitioned copy of input array with its elements rearraged in such a way that the value of the element in k-th position is in the position it would in a sorted array

The elements that are smaller than the k-th element are moved before the element, and all equal or greater are moved behind.

Syntax: np.argpartition(arr,kth,axis=-1, kind='ntroselect',order=None)

In [16]:
import numpy as np

#input array
a=np.array([[3,2,1],[4,5,8]])
print("Input array :\n ",a)

a2=np.argpartition(a,1,axis=1)
print("Output partitioned array: \n",a2)

Input array :
  [[3 2 1]
 [4 5 8]]
Output partitioned array: 
 [[2 1 0]
 [0 1 2]]


# setdiff1d()
This function find the set difference of two arrays and return the unique values in arr1 that are not in the second array.

Syntax: np.setdiff1d(arr1,arr2, assume_unique=False)



In [17]:
import numpy as np

arr1= [2,3,4,5,6]
arr2 = [1,2,3,5]
mnp=np.setdiff1d(arr1,arr2)
print(mnp)

[4 6]


# itemsize

The function returns the length of each element of array in bytes

In [18]:
import numpy as np
y= np.array([4,5,6,7,8,9],dtype = np.int8)
print( y.itemsize)
y.dtype

1


dtype('int8')

# hstack()
It is used to stack the sequence of input arrays horizontally i.e columnwise to make a single array

Syntax: np.hstack(tup)

In [19]:
import numpy as np
#input array
arr = np.array([4,5,6,7])
print("Input1 : \n", arr)

arr2 = np.array([2,3,8,9])
print("Input2 : \n",arr2)

# using the hstack 
arr3 = np.hstack((arr,arr2))
print("output: \n", arr3)

Input1 : 
 [4 5 6 7]
Input2 : 
 [2 3 8 9]
output: 
 [4 5 6 7 2 3 8 9]


# vstack()

It is used to stack the sequence of input arrays Vertically i.e columnwise to make a single array

Syntax: np.vstack(tup)

In [20]:
import numpy as np
#input array
arr4 = np.array([4,5,6,7])
print("Input1 : \n", arr4)

arr5 = np.array([2,3,8,9])
print("Input2 : \n",arr5)

# using the vstack 
arr6 = np.vstack((arr,arr5))
print("output: \n", arr6)

Input1 : 
 [4 5 6 7]
Input2 : 
 [2 3 8 9]
output: 
 [[4 5 6 7]
 [2 3 8 9]]


# hsplit()
The function  is used to split an array into multiple sub arrays horizontally(column-wise)
hsplit is equivalent to split with axis=1, the array is always split along the second axis regardless of the array dimension.

Syntax:np.hsplit(arr, indices_or_sections)

In [21]:
import numpy as np
arr = np.arange(27.0).reshape(3,3,3)
print(arr, "\n")
abc = np.hsplit(arr, 3)
print (abc)

[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]] 

[array([[[ 0.,  1.,  2.]],

       [[ 9., 10., 11.]],

       [[18., 19., 20.]]]), array([[[ 3.,  4.,  5.]],

       [[12., 13., 14.]],

       [[21., 22., 23.]]]), array([[[ 6.,  7.,  8.]],

       [[15., 16., 17.]],

       [[24., 25., 26.]]])]


# vsplit()
This function splits an array into mulyiple sub-arrays vertically (row-wise)

In [22]:
y = np.arange(8.0).reshape(2,2,2)
print(y)
x=np.vsplit(y,1) 

print(x)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
[array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])]


# View vs Shallow Copy
The difference between view and shallow copy is that :
Copy returns a new array  with the same elements of the the original  stored in a diffrent location ,where as view is the view of the original array.

In [23]:
#Creating an array
import numpy as np
num = np.array([[2,4,5,6,7,10]])
#assigning num to  abc
abc=np.copy(num)
print(abc)

[[ 2  4  5  6  7 10]]


# Deep Copy


In [24]:
import numpy as np
import copy

t = np.array([[[2,3,4],[1,4,6,],[6,7,8]]])
y = copy.deepcopy(t)
print(y)

[[[2 3 4]
  [1 4 6]
  [6 7 8]]]


# copy()
This returns an array copy of the given object.

Syntax: np.array(a, copy=True)

In [25]:
import numpy as np

#Create a numpy  array
x = np.array([[2,4,5,8], [3,6,7,9]])

#Copy contents of x to y
y = x.copy()

print("x\n", x)
print('y\n', y)


x
 [[2 4 5 8]
 [3 6 7 9]]
y
 [[2 4 5 8]
 [3 6 7 9]]


In [26]:
# Modify x
x[1,2] = 15


# Even if you modify x, y will still have the original value of x.
print("x\n", x)
print('y\n', y)


x
 [[ 2  4  5  8]
 [ 3  6 15  9]]
y
 [[2 4 5 8]
 [3 6 7 9]]


# meshgrid()
The function is used for creating a rectangular grid from a given 1-D arrayd that represent the matrix indexing

Syntax: np.meshgrid(* xi, **kwargs)


In [27]:
import numpy as np

x= np.linspace(-3,3,9)
# numpy.linspace creates an array

y=np.linspace(-8, 8,11)
x_1, y_1 = np.meshgrid(x,y)

print("x_1 matrix :")
print(x_1)
print("y_1 Matrix :")
print(y_1)

x_1 matrix :
[[-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]
 [-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]
 [-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]
 [-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]
 [-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]
 [-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]
 [-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]
 [-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]
 [-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]
 [-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]
 [-3.   -2.25 -1.5  -0.75  0.    0.75  1.5   2.25  3.  ]]
y_1 Matrix :
[[-8.  -8.  -8.  -8.  -8.  -8.  -8.  -8.  -8. ]
 [-6.4 -6.4 -6.4 -6.4 -6.4 -6.4 -6.4 -6.4 -6.4]
 [-4.8 -4.8 -4.8 -4.8 -4.8 -4.8 -4.8 -4.8 -4.8]
 [-3.2 -3.2 -3.2 -3.2 -3.2 -3.2 -3.2 -3.2 -3.2]
 [-1.6 -1.6 -1.6 -1.6 -1.6 -1.6 -1.6 -1.6 -1.6]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 1.6  1.6  1.6  1.6  1.6  1.6  1.6  1.6  1.6]
 [ 3.2  3.

# swapaxes()

It is used for interchanging two axes of an array.

Syntax: np.swapaxes (a, source,destination)

In [28]:
import numpy as np
a = np.array ([[5,6,7,8]])
np.swapaxes(a,0,1)

array([[5],
       [6],
       [7],
       [8]])

# column_stack()s

The function is used for stacking  1-D array as column into a 2-D array
It takes a sequence of 1_d arrays and stack them as columns to make a a single 2-D array.

Syntax: np.column_stack(tup)

In [29]:
import numpy as np
#Input array
x= np.array((2,4,5,6,8,6))
print("Array1 : \n ", x)

x2 = np.array((1,3,7,9,2,4))
print("Array2 : \n", x2)
#Stacking the two arrays
x3=np.column_stack((x,x2))
print("output stacked array : \n ",x3)

Array1 : 
  [2 4 5 6 8 6]
Array2 : 
 [1 3 7 9 2 4]
output stacked array : 
  [[2 1]
 [4 3]
 [5 7]
 [6 9]
 [8 2]
 [6 4]]
